# Generated by Django 4.0 on 2021-12-30 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('post_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=100, verbose_name='图片名称')),
                ('url', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Image',
            },
        ),
        migrations.CreateModel(
            name='PersonalArticle',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('H', '医务人员'), ('Z', '志愿者'), ('X', '消防员')], default='Z', max_length=1)),
                ('post_datetime', models.DateTimeField(auto_now=True)),
                ('read_count', models.PositiveBigIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.image')),
            ],
            options={
                'db_table': 'PersonalArticle',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_name', models.CharField(max_length=100, verbose_name='视频名称')),
                ('url', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Video',
            },
        ),
        migrations.CreateModel(
            name='SecondaryComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('post_datetime', models.DateTimeField(auto_now=True)),
                ('first_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'SecondaryComment',
            },
        ),
        migrations.CreateModel(
            name='Praise',
            fields=[
                ('praise_id', models.AutoField(primary_key=True, serialize=False)),
                ('isPraise', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.personalarticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'Praise',
            },
        ),
        migrations.AddField(
            model_name='personalarticle',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.video'),
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.personalarticle'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('collect_id', models.AutoField(primary_key=True, serialize=False)),
                ('isCollect', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.personalarticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'Collect',
            },
        ),
    ]
