# Generated by Django 4.0 on 2021-12-31 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_browsinghistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalarticle',
            name='image',
        ),
        migrations.RemoveField(
            model_name='personalarticle',
            name='video',
        ),
        migrations.AddField(
            model_name='personalarticle',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='图片名称'),
        ),
        migrations.AddField(
            model_name='personalarticle',
            name='video_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='视频名称'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
