# Generated by Django 4.0 on 2021-12-31 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_personalarticle_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalarticle',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='personalarticle',
            name='video_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='视频地址'),
        ),
    ]
